// <auto-generated />
using System;
using LinnworksSales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinnworksSales.WebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LinnworksSales.Data.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<long?>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("LinnworksSales.Data.Models.ItemType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("LinnworksSales.Data.Models.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("LinnworksSales.Data.Models.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CountryForeignKey");

                    b.Property<long?>("ItemTypeForeignKey");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("OrderPriority");

                    b.Property<int>("SalesChanel");

                    b.Property<DateTime>("ShipDate");

                    b.Property<decimal>("UnitCost");

                    b.Property<decimal>("UnitPrice");

                    b.Property<int>("UnitsSold");

                    b.HasKey("Id");

                    b.HasIndex("CountryForeignKey");

                    b.HasIndex("ItemTypeForeignKey");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LinnworksSales.Data.Models.Country", b =>
                {
                    b.HasOne("LinnworksSales.Data.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("LinnworksSales.Data.Models.Sale", b =>
                {
                    b.HasOne("LinnworksSales.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryForeignKey");

                    b.HasOne("LinnworksSales.Data.Models.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
